name: mini_ecommerce_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  get: ^4.7.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.5.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/icon.png

# Launcher icon configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: lib/assets/images/icon.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: lib/assets/images/icon.png
  remove_alpha_ios: true