name: Build Release APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  android-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java (Temurin 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Fetch dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release

      - name: Rename APK
        run: |
          mkdir -p build/output
          cp build/app/outputs/flutter-apk/app-release.apk build/output/Mini_ecommerce_app.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mini_ecommerce_app
          path: build/output/Mini_ecommerce_app.apk
